name: 'Slack File Upload'
description: 'An action to upload artifact to Slack.'
author: 'kibettheophilus'

branding:
  icon: 'upload'
  color: 'blue'

inputs:
  file:
    description: 'Artifact file to be uploaded to Slack'
    required: true

outputs:
  success:
    description: 'Confirms the upload was successful'

runs:
  using: node20
  main: dist/index.js
