name: 'Slack File Upload'
description: 'An action to upload artifact to Slack.'
author: 'kibettheophilus'

branding:
  icon: 'upload'
  color: 'blue'

inputs:
  token:
    description: 'Slack token'
    required: true
  file:
    description: 'Artifact file to be uploaded to Slack'
    required: true
  filename:
    description: 'Name of the artifact to be uploaded'
    required: true
  channelName:
    description: 'Channel ID where the file will be shared'
    required: false
  message:
    description: 'The message text introducing the file in specified channels'
    required: false

outputs:
  success:
    description: 'Confirms the upload was successful'

runs:
  using: node20
  main: dist/index.js
